services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.12
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ../../configs/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
volumes:
  clickhouse-data: {}
